In [1]:
import torch
import numpy as np

print(torch.__version__)

2.12.0+cu130


In [2]:
def print_tensor_info(tensor, name):
    print(f"Tensor {name} :", tensor)
    print(f"Shape of {name} :", tensor.shape)
    print(f"Dimension of {name} :", tensor.dim())

def tensor_A():
    A = torch.FloatTensor([1, 2, 3, 4, 5])
    print_tensor_info(A, "A")
    print(f"Data type of A :", A.dtype, "\n")

def tensor_B():
    B = torch.FloatTensor([[1, 2, 3], [4, 5, 6]])
    print_tensor_info(B, "B")
    print(f"Number of elements in B :", B.numel(), "\n")

def tensor_C():
    C = torch.arange(1, 13, 1).view(2, 2, 3)
    print_tensor_info(C, "C")
    print(f"Number of elements in C :", C.numel(), "\n")


if __name__ == "__main__":
    tensor_A()
    tensor_B()
    tensor_C()


Tensor A : tensor([1., 2., 3., 4., 5.])
Shape of A : torch.Size([5])
Dimension of A : 1
Data type of A : torch.float32 

Tensor B : tensor([[1., 2., 3.],
        [4., 5., 6.]])
Shape of B : torch.Size([2, 3])
Dimension of B : 2
Number of elements in B : 6 

Tensor C : tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])
Shape of C : torch.Size([2, 2, 3])
Dimension of C : 3
Number of elements in C : 12 



## Q1.
---
* (5,) : axis의 개수(rank)가 1개이고, 길이가 5인 1-D tensor 이자, element가 5개인 vector
* (2,3) : axis의 개수(rank)가 2개이고, 1st-axis의 길이는 2, 2nd-axis의 길이는 3인 2-D tensor이자, 2 by 3 matrix
* (2,2,3) : axis의 개수(rank)가 3개이고 1st-axis의 길이는 2, 2nd-axis의 길이는 2, 3rd-axis의 길이는 3인 3-D tensor
---


In [3]:
def tensor_A():
    A = torch.tensor([
        [1,  2,  3,  4],
        [5,  6,  7,  8],
        [9, 10, 11, 12]
    ])
    return A

def practice_indexing(tensor):
    print(tensor[0,0])
    print(tensor[1,2])
    print(tensor[2,3])
    print(tensor[1])
    print()
    # print(tensor[0])
    # print(tensor[0].shape)
    # print()


def practice_slicing(tensor):
    print(f"{str(tensor[0:1])} {tensor[0:1].shape}")
    print(f"{str(tensor[0:4, 0:1])} {tensor[0:4, 0:1].shape}")
    print(f"{str(tensor[0:4, 2:4])} {tensor[0:4, 2:4].shape}")
    print(f"{str(tensor[0:2])} {tensor[0:2].shape}")
    print(f"{str(tensor[1:3, 2:4])} {tensor[1:3, 2:4].shape}")
    print()
    # print(tensor[0:1])
    # print(tensor[0:1].shape)
    # print()

if __name__ == "__main__":
    A = tensor_A()
    practice_indexing(A)
    practice_slicing(A)



tensor(1)
tensor(7)
tensor(12)
tensor([5, 6, 7, 8])

tensor([[1, 2, 3, 4]]) torch.Size([1, 4])
tensor([[1],
        [5],
        [9]]) torch.Size([3, 1])
tensor([[ 3,  4],
        [ 7,  8],
        [11, 12]]) torch.Size([3, 2])
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]]) torch.Size([2, 4])
tensor([[ 7,  8],
        [11, 12]]) torch.Size([2, 2])



## Q2.
---
* print(A[0]) : 0번째 index(원소)를 선택
* print(A[0:1]) : 0번째부터 1번 전까지 slicing
* *i.e.* : indexing은 axis가 제거되어 차원이 축소되지만,  slicing은 차원이 유지됨
---

In [4]:
def Tensor():
    A = torch.tensor([[1,2],[3,4]])
    B = torch.tensor([[5,6],[7,8]])
    return A,B

def Concat(tensor_1, tensor_2):
    C = torch.cat([tensor_1, tensor_2], dim=0)
    print(C, C.shape)
    
    D = torch.cat([tensor_1, tensor_2], dim=1)
    print(D, D.shape)

if __name__ == "__main__":
    A,B = Tensor()
    Concat(A,B)

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]]) torch.Size([4, 2])
tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]]) torch.Size([2, 4])


# Q3. 
---
* 2-D tensor가 결합되는 방향의 차이로, dim = 0 은 row, dim = 1은 column방향으로 결합된다.
* 따라서 shape 또한 dim = 0 은 4 * 2로, dim = 1 은 2 * 4인 shape을 가진다.
---

In [5]:
def stack(tensor_1, tensor_2):
    C = torch.stack([tensor_1, tensor_2], dim = 0)
    D = torch.stack([tensor_1, tensor_2], dim = 1)

    print(C, C.shape)
    print()
    print(D, D.shape)

if __name__ == "__main__":
    A ,B = Tensor()
    stack(A,B)

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]]) torch.Size([2, 2, 2])

tensor([[[1, 2],
         [5, 6]],

        [[3, 4],
         [7, 8]]]) torch.Size([2, 2, 2])


# Q4.
---
* torch.cat() : 기존 axis를 사용하여 확장함, 차원이 유지됨
* torch.stack() : 새로운 axis를 생성하여 확장, 새로운 차원이 생성됨
---


In [22]:
def ViewAndReshape():
    A = torch.arange(1,13,1)
    print(A)
    print(A.shape)
    print()
    return A

def ThreeByFour(tensor_view):
    B = tensor_view.view(3,4)
    print(B)
    print(B.shape)
    print()

def TwoByTwoByThree(tensor_reshape):
    C = tensor_reshape.reshape(2,2,3)
    print(C)
    print(C.shape)
    print()

    
# def IfItCan(tensor_impossible):
#     ViewAndReshape()
#     D = tensor_impossible.view(5,3)
#     print(D, D.shape)

    

if __name__ == "__main__":
    A = ViewAndReshape()
    ViewAndReshape()
    ThreeByFour(A)
    TwoByTwoByThree(A)
    # IfItCan(A)


tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])
torch.Size([12])

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])
torch.Size([12])

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
torch.Size([3, 4])

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])
torch.Size([2, 2, 3])



# Q5. 

---
* 불가능하다.
* A.numel  = 12이고, 5 by 3인 tensor의 element의 개수는 15개 이기에, 원소의 집합이 보존되지 않음
---


In [23]:
A = torch.arange(1,25)
print(f"{A},\n, {A.shape}, \n")

B = A.reshape(4, -1)
print(f"{B},\n, {B.shape}")


tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 20, 21, 22, 23, 24]),
, torch.Size([24]), 

tensor([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12],
        [13, 14, 15, 16, 17, 18],
        [19, 20, 21, 22, 23, 24]]),
, torch.Size([4, 6])


# Q6.
---
* 6 column
* A.numel = 24이고 reshape 내부에 입력된 인자 4를 기준으로 자동계산되므로, 4 by 6 tensor로 계산됨
---

In [24]:
def SqueezeAndUnsqueeze():     
    A = torch.tensor([1,2,3,4])
    print(A.shape)
    print()
     
    B = A.unsqueeze(0)
    C = A.unsqueeze(1)

    print(f"{A.shape}, {B.shape}, {C.shape}, \n")
     
    D = torch.ones(1,3,1)
    print(f"{D.shape}, \n")

    E = D.squeeze()
    print(f"{E.shape}, \n")

if __name__ == "__main__":
    SqueezeAndUnsqueeze()
         

torch.Size([4])

torch.Size([4]), torch.Size([1, 4]), torch.Size([4, 1]), 

torch.Size([1, 3, 1]), 

torch.Size([3]), 



# Q7.
---
* squeeze() : axis의 length가 1인 차원 제거(축소)
* unsqueeze() : 새로운 axis 추가, argument로 axis를 추가할 축 지정 
---

In [25]:
def TensorOperation():
    A = torch.tensor([10., 20., 30., 40.])
    B = torch.tensor([1., 2., 3., 4.])
    return A,B

def TensorAndTensorOperation(tensor_A, tensor_B):
    
    print(tensor_A + tensor_B)
    print(tensor_A - tensor_B)
    print(tensor_A * tensor_B)
    print(tensor_A / tensor_B)
    print(tensor_A ** 2)

def TensorAndScalarOperation(tensor_A):
    print(tensor_A + 10)
    print(tensor_A * 2)
    print(tensor_A / 10)    

if __name__ == "__main__":
    A,B = TensorOperation()
    TensorAndTensorOperation(A,B)
    TensorAndScalarOperation(A)


tensor([11., 22., 33., 44.])
tensor([ 9., 18., 27., 36.])
tensor([ 10.,  40.,  90., 160.])
tensor([10., 10., 10., 10.])
tensor([ 100.,  400.,  900., 1600.])
tensor([20., 30., 40., 50.])
tensor([20., 40., 60., 80.])
tensor([1., 2., 3., 4.])


# Q8.
---
* tensor의 형태( _e.j._ 차원, rank, 축의 개수)는 바뀌지 않고 element-wise한 연산으로 진행됨
---

In [26]:
def Multiplication():
    A = torch.tensor([
    [1., 2.],
    [3., 4.]
    ])

    B = torch.tensor([
        [5., 6.],
        [7., 8.]
    ])
    return A,B

def ElementWiseMultiplication(tensor_A, tensor_B):
    C = tensor_A * tensor_B
    print("Element-wise Multiplication")
    print("-" * 20)
    print(C)
    print("-" * 20)

def MatrixMultiplication_1(tensor_A, tensor_B):
    D = tensor_A @ tensor_B
    print("\n Matrix Multiplication")
    print("-" * 20)
    print(D)
    print("-" * 20)

def MatrixMultiplication_2(tensor_A, tensor_B):
    D = torch.matmul(tensor_A, tensor_B)
    print("\n Matrix Multiplication")
    print("-" * 20)
    print(D)
    print("-" * 20)


if __name__ == "__main__":
    A, B = Multiplication()
    ElementWiseMultiplication(A,B)
    MatrixMultiplication_1(A,B)
    MatrixMultiplication_2(A,B)



Element-wise Multiplication
--------------------
tensor([[ 5., 12.],
        [21., 32.]])
--------------------

 Matrix Multiplication
--------------------
tensor([[19., 22.],
        [43., 50.]])
--------------------

 Matrix Multiplication
--------------------
tensor([[19., 22.],
        [43., 50.]])
--------------------


# Q9. 
---
* *가 수행하는 연산은 element-wise한 곱셈(Hadamard Product)이므로, 같은 위치에 있는 원소끼리만 곱함
* @가 수행하는 연산은 행렬곱(Matrix Product)이므로, A•B는  A(i by j)의 row, B(j by k)의 column을 곱해 새로운 행렬은 만드는 연산임.

---

In [27]:
def Transpose():
    A = torch.tensor([
        [1., 2., 3.],
        [4., 5., 6.]
    ])

    B = A.T

    print(A)
    print(A.shape)
    print()
    print(B)
    print(B.shape)

if __name__ == "__main__":
    Transpose()


tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.Size([2, 3])

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
torch.Size([3, 2])


# Q10.
---
* shape이 (2,3)인 tensor의 두 axis가 서로 바뀜
---

In [28]:
def StatisticalOperation():
    A = torch.tensor([
        [10., 20., 30.],
        [40., 50., 60.],
        [70., 80., 90.]
    ])
    return A

def PrintOperation(tensor_A):
    print(torch.sum(tensor_A))
    print(torch.mean(tensor_A))
    print(torch.max(tensor_A))
    print(torch.min(tensor_A))

if __name__ == "__main__":
    A = StatisticalOperation()
    PrintOperation(A)

tensor(450.)
tensor(50.)
tensor(90.)
tensor(10.)


In [29]:
def DimensionOperation():
    A = torch.tensor([
        [10., 20., 30.],
        [40., 50., 60.],
        [70., 80., 90.]
    ])

    print(torch.sum(A, dim=0))
    print(torch.mean(A, dim=0))
    print()
    print(torch.sum(A, dim=1))
    print(torch.mean(A, dim=1))
    print("\n", "-" * 20, "\n")
    print(torch.sum(A, dim=0).shape)
    print(torch.mean(A, dim=0).shape)
    print()
    print(torch.sum(A, dim=1).shape)
    print(torch.mean(A, dim=1).shape)


if __name__ == "__main__":
    DimensionOperation()


tensor([120., 150., 180.])
tensor([40., 50., 60.])

tensor([ 60., 150., 240.])
tensor([20., 50., 80.])

 -------------------- 

torch.Size([3])
torch.Size([3])

torch.Size([3])
torch.Size([3])


# Q11.
---
* dim = 0 : 각 column 내부의 원소들끼리 연산됨
* dim = 1 : 각 row 내부의 원소들끼리 연산됨
* 합산 혹은 평균값을 도축하여 차원이 축소되므로 shape은 서로 동일함
---

In [30]:
def LinkUpPractice():
    # 1. 크기가 (3, 4)인 Tensor A 생성
    A = torch.arange(1.,13.,1).view(3,4) 
    # 자료형 미지정시, A.type은 integer이기에 평균 계산 시 오류 발생하므로 float로 생성

    print(f"Tensor A:\n{A}\n")
    print(f"A shape: {A.shape}\n")


    # 2. Tensor A를 전치하여 Tensor B 생성
    B = A.T

    print(f"Tensor B (A의 전치):\n{B}\n")
    print(f"B shape: {B.shape}\n")


    # 3. Tensor A와 B를 행렬 곱셈하여 Tensor C 생성
    C = A @ B

    print(f"Tensor C (A @ B):\n{C}\n")
    print(f"C shape: {C.shape}\n")


    # 4. Tensor C의 각 행에 대해 평균을 계산하여 Tensor D에 저장
    D = torch.mean(C, dim = 1)

    print(f"Tensor D (C의 행별 평균):\n{D}\n")
    print(f"D shape: {D.shape}\n")

    # D = torch.mean(C)
    # print(f"Tensor D (C의 평균):\n{D}\n")
    # print(f"D shape: {D.shape}\n")


    # 5. Tensor D의 모든 원소의 합을 계산
    final_sum = torch.sum(D)

    print(f"최종 결과값: {final_sum}\n")

if __name__ == "__main__":
    LinkUpPractice()

Tensor A:
tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])

A shape: torch.Size([3, 4])

Tensor B (A의 전치):
tensor([[ 1.,  5.,  9.],
        [ 2.,  6., 10.],
        [ 3.,  7., 11.],
        [ 4.,  8., 12.]])

B shape: torch.Size([4, 3])

Tensor C (A @ B):
tensor([[ 30.,  70., 110.],
        [ 70., 174., 278.],
        [110., 278., 446.]])

C shape: torch.Size([3, 3])

Tensor D (C의 행별 평균):
tensor([ 70., 174., 278.])

D shape: torch.Size([3])

최종 결과값: 522.0



# Q12.
---
* A(3 by 4 matrix) * B(4 by 3 matrix)이므로 3 by 3 matrix인 C가 산출됨
---

# Q13.
---
* A의 row와 B의 column이 각각 inner product로 연산되어, 9개(3 by 3)의 원소가 만들어짐
---

# Q14.
---
* torch.mean(C) : 해당 tensor에 있는 모든 elements의 평균
* torch.mean(C, dim = 1) : 해당 tensor 내 행별 평균
---

In [31]:
def ApplicationPractice():
    features = torch.tensor([
        [170., 65., 20.],
        [180., 75., 22.],
        [165., 55., 21.],
        [175., 70., 23.]
    ])

    print(features)
    print(features.shape)
    print(features.dim())
    print()
    print(torch.mean(features, dim = 0)) # 문제 16-1 특징별 평균
    print(torch.mean(features, dim = 1)) # 문제 16-2 학생별 평균

if __name__ == "__main__":
    ApplicationPractice()

tensor([[170.,  65.,  20.],
        [180.,  75.,  22.],
        [165.,  55.,  21.],
        [175.,  70.,  23.]])
torch.Size([4, 3])
2

tensor([172.5000,  66.2500,  21.5000])
tensor([85.0000, 92.3333, 80.3333, 89.3333])


# Q15.
---
* 4 : row(학생)의 수
* 3 : column(특징)의 개수
---

# Q16.
---
* 모델 설계 시, 각 axis를 무엇으로 설정할 것인지에 대한 기준이 명확해야 학습(supervised learning)에 대한 효과가 극대화되기 떄문
* Big Data 3V Theorem
---

In [32]:
def Error_1():
    A = torch.arange(10)
    B = A.reshape(3, 4)

# Q17.
---
* A의 총 원소의 개수는 10개이지만, B는 12개이므로 오류가 발생함

> 수정된 코드
>> ```  A = torch.arange(12) ```
>> ``` B = A.reshape(3, 4) ```
---

In [36]:
A = torch.tensor([
    [1, 2, 3],
    [4, 5, 6]
])
print(A.shape)

B = torch.tensor([
    [1, 2],
    [3, 4],
    [5, 6]      # 2 by 2 -> 3 by 2 로 변경
])
print(B.shape)

C = A @ B


torch.Size([2, 3])
torch.Size([3, 2])


# Q18.
---
* A는 2 by 3, B는 2 by 2이므로 서로 행렬곱 불가능
* B를 3 by n, A를 n by 2로 바꾼다면 행렬곱 가능
---